### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ForeverK87** [nimble-dev/compareMCMCs#1]
Hello, how could we install the compareMCMCs package? So far, everything I tried doesn't seem to work!

**Comment by perrydv** [comment]
Hi @ForeverK87 sorry for the slow reply.  I added a note at the bottom of the README showing how to install from github.  It is:

```r
library(devtools)
install_github("nimble-dev/compareMCMCs", subdir = "compareMCMCs")
```

**Comment by ForeverK87** [comment]
That works great @perrydv , thank you very much!
