### ISSUE TITLE
Checks for (niter, burnin, thinning) in compareMCMC.R comes from old NIMBLE version

### ISSUE THREAD

**Issue by salleuska** [nimble-dev/compareMCMCs#11]
In `compareMCMCs.R` the number of saved samples is computed discarding the burnin *post-thinning*, but form NIMBLE 0-6-11 the burnin is discared *pre-thininng*.

I've commented out the check in `stan_support` branch, but this will deserve some attention in the future. 

https://github.com/nimble-dev/compareMCMCs/blob/80618426697aae8f25e6cc61a9cb5891634b9498/compareMCMCs/R/compareMCMCs.R#L86

**Comment by perrydv** [comment]
This has been addressed.
