### ISSUE TITLE
Empty test file

### ISSUE THREAD

**Issue by rowlandseymour** [nimble-dev/compareMCMCs#14]
The test file for the Stan test is empty.

The permalink is 
https://github.com/nimble-dev/compareMCMCs/blob/7faa8c1cb251a5a20e4f5c744dd73b61ddf955ac/compareMCMCs/tests/testthat/test-stan.R

openjournals/joss-reviews#3844

**Comment by salleuska** [comment]
Thanks @rowlandseymour !

@perrydv We ended up putting stan tests in the "general" file `test-compareMCMCs.R`. So I guess we may just want to remove that `test-stan.R`. Just mentioning because at first I did not remember this!

**Comment by perrydv** [comment]
Fixed.

openjournals/joss-reviews#3844
