### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by rowlandseymour** [nimble-dev/compareMCMCs#18]
One requirement for JOSS is that you have contributor guidelines. I can't find any currently for this package. Here's an example of some from a recently accepted JOSS paper

https://github.com/ejikeugba/serp/blob/43049d3c8fd55f51952e5354ccaa4997383442d0/contributing.md

openjournals/joss-reviews#3844

**Comment by perrydv** [comment]
Hi @rowlandseymour Thanks for catching that.  We added contributor guidelines at the end of the README.md.
