### ISSUE TITLE
logging cpu/machine details

### ISSUE THREAD

**Issue by tbrown122387** [nimble-dev/compareMCMCs#19]
Hey, you all mention a [few things that are timed](https://htmlpreview.github.io/?https://github.com/nimble-dev/compareMCMCs/blob/master/compareMCMCs/doc/compareMCMCs.html#what-is-timed) to help compare mcmcs. Do you guys also store information about the computer running the code? These times are highly dependent on that. 

openjournals/joss-reviews#3844

**Comment by perrydv** [comment]
Hi @tbrown122387.  That's a great idea.  Thanks.  I added an option called `sessionInfo`, default `TRUE`, that will record the output of `sessionInfo()` in the `MCMCresult` object.  At the moment nothing is done with this, but it is there for inspection.  I will add an example in the vignette when I revise that.  One could go further with machine and session information, but this seems like a basic first step.  They would allow a user to check the provenance of various runs they may be comparing to each other.
