### ISSUE TITLE
vignette formatting typo

### ISSUE THREAD

**Issue by tbrown122387** [nimble-dev/compareMCMCs#20]
Looks like something is going on with the phrase 

We can see that the parameter is now log_a rather than a. The use of backticks in "log(\a`)" ensures thata` is evaluated as a variable and is described more below.

This is in the vignette in the section "Converting parameters to match each other across different MCMCs."

openjournals/joss-reviews#3844

**Comment by perrydv** [comment]
Thanks for catching that @tbrown122387.  This is fixed now.
