### ISSUE TITLE
does nimble need to be a dependency?

### ISSUE THREAD

**Issue by tbrown122387** [nimble-dev/compareMCMCs#22]
This is more of a question:

What happens if we remove `nimble` as a dependency? Should it be? If this is a standalone project, it might be desirable to remove it. Also, it looks like there are certain variable names that are shared  (e.g. `compareMCMCs()`), so you'll need to be vigilant about using the `::` operator.

https://github.com/nimble-dev/compareMCMCs/blob/7faa8c1cb251a5a20e4f5c744dd73b61ddf955ac/compareMCMCs/DESCRIPTION#L17

openjournals/joss-reviews#3844

**Comment by perrydv** [comment]
@tbrown122387 I did clean up other entries in Depends vs Imports, but it looks like we do need `nimble` in Depends. It's related to how nimble does a lot of R code generation and evaluation.  For example, it makes on-the-fly function definitions to use in models and class definitions for models and other components.  This brings up issues to do with `nimble` more than `compareMCMCs` so I won't go further.  If possible in the future we will be able to move `nimble` from Depends to Imports.

The reason for the duplication of the name `compareMCMCs` across packages is that the idea started as a function in `nimble` and now is being separated into its own package here (and completely re-designed).  So `compareMCMCs` in `nimble` just tells users they need this new package.  Once this is released, we will eventually remove `compareMCMCs` from `nimble`.
