### ISSUE TITLE
Tests are not set up to be run via R CMD check and other automated CI tools

### ISSUE THREAD

**Issue by fabian-s** [nimble-dev/compareMCMCs#24]
please run `usethis::use_testthat` on your package repo, this will 

- add `testthat` to Suggests field in DESCRIPTION 
- add [testthat.txt](https://github.com/nimble-dev/compareMCMCs/files/7486589/testthat.txt) as `testthat.R` to your top-level `tests`-directory

**Comment by perrydv** [comment]
Thanks @fabian-s This is done.
