### ISSUE TITLE
Modify Stan sampling_args to work with code (character string of model)

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/compareMCMCs#29]
@perrydv @salleuska At present, the Stan implementation **requires** a user to provide a file (`.stan`) for the Stan model.  This is enforced in checking of the `externalMCMCinfo` argument, and also with the Stan `sampling_args`.

I think it would be nice to also allow the Stan model as a character string, which is provided as the `code` argument to `rstan::sampling`.

**Comment by perrydv** [comment]
HI @danielturek That's a good point of how people would want to use Stan.  I changed the error-trapping in `MCMCdef_stan_impl` to allow the possibility that a `model_code` element (I think that's what you meant?) (in the `stan_model_args` element of the `stan` element of `externalMCMCinfo`) was provided.  Now that should go through and work.

**Comment by perrydv** [comment]
Looks like this was fixed a while ago, so I'm closing it.
