### ISSUE TITLE
thinning error in MCMCdef_jags?

### ISSUE THREAD

**Issue by salleuska** [nimble-dev/compareMCMCs#8]
https://github.com/nimble-dev/compareMCMCs/blob/a9ec246594c9e3c3ddf1e50e613aa4033ae3057a/compareMCMCs/R/MCMCdef_stan.R#L68

As it is coded here, it seems to me that `floor(niter/thin)` samples after burnin are taken. Instead, we want samples every `thin` interval. Shouldn't it be  `seq(burnin, niter, by = thin)`?

**Comment by perrydv** [comment]
I think this is now in a different place.  I'd have to check, but I think what happens is that thinning is applied in the call to `rjags::coda.samples`.  So the tempArray already has thinned samples, and `floor(niter/thin)` should just be the number of rows of tempArray.  Starting at burnin+1 means that burnin is applied post-thinning, which I think is what we decided to do.

**Comment by perrydv** [comment]
This has been ironed out.
